version: '3.8'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/mankousheh
      - JWT_SECRET=${JWT_SECRET:-supersecret}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL:-}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY:-}
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: